apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: rag-service
  name: rag-service
spec:
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8004
  selector:
    io.kompose.service: rag-service
